/*
 * File: fuzz_parser.c
 * Purpose: libFuzzer entry point for fuzzing VFS filename parsing and ELF header loading.
 *
 * This file is part of the esdumanOS test suite.
 */
#include "elf.h"

// =========================================================================
// libFuzzer Entry Point
// LLVM calls this function thousands of times per second with random Data and Size.
// Goal: Determine if corrupted data causes the kernel to crash.
// =========================================================================

/*
 * Function: LLVMFuzzerTestOneInput
 * Purpose: Fuzz tests the Virtual File System (VFS) and ELF loader to ensure the kernel can withstand malformed or malicious inputs without crashing.
 * Mechanism: Evaluates random bytes generated by libFuzzer. It first tests VFS filename bounds and character filtering, 
 *            then attempts to parse the payload as an ELF header, checking for integer overflows and out-of-bounds reads during program header iteration.
 * Expected Behavior: Returns 0 unconditionally to signal libFuzzer that the kernel gracefully handled the input. If a memory violation 
 *                    occurs, AddressSanitizer (ASan) will intervene and crash the process, indicating a vulnerability.
 * Edge Cases: Tests ultra-long filenames, non-printable filename characters, manipulated ELF segment counts (e.g., 65000), 
 *             and corrupted ELF program header offsets designed to trigger integer overflows.
 */
int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size) {
    
    // ---------------------------------------------------------
    // TEST 1: VFS Filename Parsing Fuzzing
    // ---------------------------------------------------------
    // What happens if excessively long or corrupted filenames are sent to VFS?
    
    // Process input specifically sized for filename testing (under 500 bytes to focus the fuzzing space).
    if (Size > 0 && Size < 500) {
        char filename[256];
        // Calculate a safe copy size to prevent buffer overflows on the fixed 256-byte stack array.
        // Limit the copy to 255 bytes to guarantee space for the null terminator.
        size_t copy_size = Size < 255 ? Size : 255;
        
        // Copy the fuzz data into the local filename buffer to simulate a userland path string.
        for(size_t i = 0; i < copy_size; i++) {
            filename[i] = Data[i];
        }
        // Force null-termination at the end of the copied payload to ensure standard string functions operate safely.
        filename[copy_size] = '\0';
        
        // VFS loop simulating character checks in the name:
        volatile int valid = 1;
        // Iterate through the simulated filename to validate character constraints.
        for (size_t i = 0; i < copy_size; i++) {
            // Check if the character falls outside the printable ASCII range (below 32 or above 126).
            if (filename[i] < 32 || filename[i] > 126) {
                // Invalidate the filename to simulate the kernel rejecting non-printable or dangerous characters.
                valid = 0; // Non-printable character protection
            }
        }
    }

    // ---------------------------------------------------------
    // TEST 2: ELF Header and Program Header (Phdr) Fuzzing
    // ---------------------------------------------------------
    // Dangerous header reading portion in the load_and_exec_elf() function.
    // Will paging crash if the fuzzer provides correct Magic Number but corrupted offsets?
    
    // Ensure the fuzz payload is at least as large as an ELF header before attempting to parse it.
    if (Size >= sizeof(elf32_ehdr_t)) {
        // Cast the raw fuzz data directly into an ELF header structure to simulate in-memory loading.
        elf32_ehdr_t *ehdr = (elf32_ehdr_t *)Data;
        
        // Deep dive only for random data containing the "ELF" prefix!
        // Verify the ELF magic bytes (0x7F, 'E', 'L', 'F') to mimic the kernel's initial ELF validation check.
        if (ehdr->e_ident[0] == 0x7F && ehdr->e_ident[1] == 'E' &&
            ehdr->e_ident[2] == 'L' && ehdr->e_ident[3] == 'F') {
            
            // Extract the program header table offset provided by the potentially malicious payload.
            uint32_t phoff = ehdr->e_phoff;  // Program Header Offset
            // Extract the number of program header entries. The fuzzer might inject an absurdly high value here.
            uint16_t phnum = ehdr->e_phnum;  // Number of segments (e.g., Fuzzer can set this to 65000!)
            
            // Try to loop phnum times (Integer Overflow or Out-of-Bounds Read test)
            // If the kernel lacks size checks, libFuzzer will immediately crash it with ASan!
            for (int i = 0; i < phnum; i++) {
                // Calculate the byte size of the current chunk to offset into the program header table.
                uint32_t chunk_size = i * sizeof(elf32_phdr_t);
                // Compute the absolute offset of the target program header entry within the payload.
                uint32_t offset = phoff + chunk_size;
                
                // SAFE BOUNDS CHECKING (Integer Overflow Protected)
                // 1. offset < phoff -> Did the addition overflow and wrap to zero? (Overflow check)
                // 2. offset >= Size -> Is the offset larger than the file size?
                // 3. Size - offset < sizeof(elf32_phdr_t) -> Is the remaining space sufficient to read 32 bytes?
                if (offset < phoff || offset >= Size || Size - offset < sizeof(elf32_phdr_t)) {
                    // Abort parsing this ELF structure if any boundary check fails, simulating kernel rejection of a malformed binary.
                    break; // Hacker attack detected! Abort operation.
                }

                // If reached here, it is mathematically 100% safe.
                // Cast the safe, validated offset within the payload into a program header structure.
                elf32_phdr_t *phdr = (elf32_phdr_t *)(Data + offset);
                
                // Read the segment type and virtual address to force memory access, verifying the pointer is truly valid.
                volatile uint32_t type = phdr->p_type; 
                volatile uint32_t vaddr = phdr->p_vaddr;
                
                // Suppress compiler warnings for unused volatile variables.
                (void)type;
                (void)vaddr;
            }
        }
    }

    // Returning 0 tells the fuzzer "System did not crash, great!"
    return 0; 
}